### ISSUE TITLE
Oil Production Layout

### ISSUE THREAD

**Issue by mlbelobraydi** [mlbelobraydi/TXRRC_data_harvest#14]
Capturing the oil production layout

**Comment by mlbelobraydi** [comment]
@bpmcdowell11, please make sure to upload the layout you have complete here.

**Comment by bpmcdowell11** [comment]
Here you go. It's still a little rough, but close enough for now. 
[RRC oil ledger tuples.xlsx](https://github.com/mlbelobraydi/TXRRC_data_harvest/files/5240968/RRC.oil.ledger.tuples.xlsx)

**Comment by mlbelobraydi** [comment]
[RRC_oil_ledger_tuples.xlsx](https://github.com/mlbelobraydi/TXRRC_data_harvest/files/5293714/RRC_oil_ledger_tuples.xlsx)

Minor changes. need to confirm the date formatted sections. Also need to add the correct number of decimals to comp3 fields.
